import { ServiceData } from "../types/portal.types";

export const SERVICES: ServiceData[] = [
  {
    id: "bidding",
    title: "입찰 공고",
    description: "공공·민간 입찰 공고 수집 · 점수화 · 알림",
    host: "bid.platformers.kr",
    href: "/services/bidding/index.php",
    searchKeywords: "입찰 공고 bid",
    newTab: false,
    iconType: "bidding",
    healthKey: "bidding",
  },
  {
    id: "meeting",
    title: "회의록 자동화",
    description: "회의 녹취 업로드 → 요약 · 결정사항 · 할일",
    host: "meeting.platformers.kr",
    href: "/meeting",
    searchKeywords: "회의록 meeting 녹음",
    newTab: false,
    iconType: "meeting",
    healthKey: "meeting",
  },
  {
    id: "news",
    title: "교육 뉴스",
    description: "RSS · NewsAPI 기반 교육 분야 뉴스 수집",
    host: "news.platformers.kr",
    href: "/services/news-api/preview.html",
    searchKeywords: "뉴스 news 교육",
    newTab: false,
    iconType: "news",
    healthKey: "news",
  },
  {
    id: "newsletter",
    title: "교육 뉴스레터",
    description: "블로그 링크 → HTML 뉴스레터 생성 · 미리보기 · 메일 발행",
    host: "newsletter.platformers.kr",
    href: "/newsletter",
    searchKeywords: "뉴스레터 newsletter 교육 메일 소식지",
    newTab: false,
    iconType: "newsletter",
    healthKey: "newsletter",
  },
  {
    id: "ppt",
    title: "PPT·제안서",
    description: "문서 업로드 → HTML·PPT 제안서 자동 생성",
    host: "ppt.platformers.kr",
    href: "/ppt",
    searchKeywords: "ppt 제안서 proposal",
    newTab: false,
    iconType: "ppt",
    healthKey: "ppt",
  },
  {
    id: "crayon",
    title: "크레용스쿨 대시보드",
    description: "크레용스쿨 제품·콘텐츠 통합 대시보드",
    host: "crayon.platformers.kr",
    href: "/services/dashboard/index.html",
    searchKeywords: "crayon 크레용스쿨 대시보드",
    newTab: false,
    iconType: "crayon",
    healthKey: "crayon",
  },
  {
    id: "fairytale",
    title: "e-book",
    description: "16컷 동화 이미지 분할 · 편집 · ZIP·Teams 출력",
    host: "fairytale.platformers.kr",
    href: "/ebook",
    searchKeywords: "ebook e-book fairytale 동화",
    newTab: false,
    iconType: "fairytale",
    healthKey: "fairytale",
  },
];

export const SERVICE_LABEL: Record<string, string> = {
  bidding: "입찰 공고",
  meeting: "회의록",
  news: "뉴스",
  newsletter: "교육 뉴스레터",
  ppt: "PPT·제안서",
  crayon: "크레용스쿨 대시보드",
  fairytale: "e-book",
  portal: "포탈",
};
